// <auto-generated />
using LLServer.Gacha.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LLServer.Gacha.Database.Migrations
{
    [DbContext(typeof(GachaDbContext))]
    [Migration("20240103001248_Change relationship structure")]
    partial class Changerelationshipstructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4");

            modelBuilder.Entity("LLServer.Gacha.Database.GachaCard", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("characterIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rarityIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("GachaCards");
                });

            modelBuilder.Entity("LLServer.Gacha.Database.GachaTable", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GachaCardid")
                        .HasColumnType("TEXT");

                    b.Property<string>("characterIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isValid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("maxRarity")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("GachaCardid");

                    b.ToTable("GachaTables");
                });

            modelBuilder.Entity("LLServer.Gacha.Database.GachaTableCard", b =>
                {
                    b.Property<string>("GachaTableId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GachaCardId")
                        .HasColumnType("TEXT");

                    b.HasKey("GachaTableId", "GachaCardId");

                    b.ToTable("GachaTableCard");
                });

            modelBuilder.Entity("LLServer.Gacha.Database.GachaTable", b =>
                {
                    b.HasOne("LLServer.Gacha.Database.GachaCard", null)
                        .WithMany("gachaTables")
                        .HasForeignKey("GachaCardid");
                });

            modelBuilder.Entity("LLServer.Gacha.Database.GachaTableCard", b =>
                {
                    b.HasOne("LLServer.Gacha.Database.GachaTable", "GachaTable")
                        .WithMany("GachaTableCards")
                        .HasForeignKey("GachaTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GachaTable");
                });

            modelBuilder.Entity("LLServer.Gacha.Database.GachaCard", b =>
                {
                    b.Navigation("gachaTables");
                });

            modelBuilder.Entity("LLServer.Gacha.Database.GachaTable", b =>
                {
                    b.Navigation("GachaTableCards");
                });
#pragma warning restore 612, 618
        }
    }
}
