// <auto-generated />
using LLServer.Gacha.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LLServer.Gacha.Database.Migrations
{
    [DbContext(typeof(GachaDbContext))]
    [Migration("20240103114631_Gacha table relationship")]
    partial class Gachatablerelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4");

            modelBuilder.Entity("GachaCardGachaTable", b =>
                {
                    b.Property<string>("cardsid")
                        .HasColumnType("TEXT");

                    b.Property<string>("gachaTablesid")
                        .HasColumnType("TEXT");

                    b.HasKey("cardsid", "gachaTablesid");

                    b.HasIndex("gachaTablesid");

                    b.ToTable("GachaCardGachaTable");
                });

            modelBuilder.Entity("LLServer.Gacha.Database.GachaCard", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<int>("cardType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("characterIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rarityIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("GachaCards");
                });

            modelBuilder.Entity("LLServer.Gacha.Database.GachaTable", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("characterIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isValid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("maxRarity")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("GachaTables");
                });

            modelBuilder.Entity("GachaCardGachaTable", b =>
                {
                    b.HasOne("LLServer.Gacha.Database.GachaCard", null)
                        .WithMany()
                        .HasForeignKey("cardsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LLServer.Gacha.Database.GachaTable", null)
                        .WithMany()
                        .HasForeignKey("gachaTablesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
